# Fastly VCL service that fronts the GCP Cloud Functions telemetry API at
# cdn.christianbrown.uk. This models the EXISTING service (id below), reconciled
# against `terraform plan` after import so the plan is clean.
#
#   terraform import fastly_service_vcl.cdn 7ieJm1LpaPnVCNb3tzURac
#
# Service id (for reference): 7ieJm1LpaPnVCNb3tzURac

# The shared-secret gate value, read from the same Secret Manager secret the
# Cloud Function reads (single source of truth). Never stored in this repo or CI.
data "google_secret_manager_secret_version" "request_auth" {
  secret  = "FASTLY_REQUIRED_HEADER_VALUE"
  project = "christianbrown"
}

resource "fastly_service_vcl" "cdn" {
  name = "GCP Cloud Functions API"

  default_ttl        = 3600
  stale_if_error     = true
  stale_if_error_ttl = 43200

  # Fastly-managed TLS aliases + the real hostname.
  domain { name = "cdn.christianbrown.uk" }
  domain { name = "cb-api.global.ssl.fastly.net" }
  domain { name = "christianbrown.global.ssl.fastly.net" }

  backend {
    name              = "GCP Cloud functions"
    address           = "europe-west2-christianbrown.cloudfunctions.net"
    port              = 443
    use_ssl           = true
    ssl_check_cert    = true
    ssl_cert_hostname = "europe-west2-christianbrown.cloudfunctions.net"
    ssl_sni_hostname  = "europe-west2-christianbrown.cloudfunctions.net"
    override_host     = "europe-west2-christianbrown.cloudfunctions.net"
    shield            = "lon-london-uk"
    weight            = 100
  }

  # HSTS on responses.
  header {
    name          = "Generated by force TLS and enable HSTS"
    type          = "response"
    action        = "set"
    destination   = "http.Strict-Transport-Security"
    source        = "\"max-age=31557600\""
    ignore_if_set = false
    priority      = 100
  }

  # Inject the shared-secret gate header so the origin Cloud Function accepts the
  # request without the browser ever seeing it. Value is read from Secret Manager
  # at plan/apply time — never hardcoded or committed.
  header {
    name          = "Set X-Request-Auth"
    type          = "request"
    action        = "set"
    destination   = "http.X-Request-Auth"
    source        = "\"${data.google_secret_manager_secret_version.request_auth.secret_data}\""
    ignore_if_set = false
    priority      = 10
  }

  # Strip query strings service-wide (also protects the 1-instance origin from
  # query-varied cache-busting).
  header {
    name          = "Remove querystrings"
    type          = "request"
    action        = "set"
    destination   = "url"
    source        = "req.url.path"
    ignore_if_set = false
    priority      = 10
  }

  request_setting {
    name          = "Generated by force TLS and enable HSTS"
    force_ssl     = true
    force_miss    = false
    max_stale_age = 0
  }

  # --- Per-client rate limiter. REQUIRES Fastly to enable "VCL rate limiting"
  # on this service first (support/account request — not self-serve). Until then,
  # activating these fails validation. Once enabled, uncomment and apply.
  # (Staged earlier as the never-activated service version 14.)
  #
  # snippet {
  #   name     = "rl_telemetry_init"
  #   type     = "init"
  #   content  = file("${path.module}/vcl/rl_telemetry_init.vcl")
  # }
  # snippet {
  #   name     = "rl_telemetry_recv"
  #   type     = "recv"
  #   priority = 110
  #   content  = file("${path.module}/vcl/rl_telemetry_recv.vcl")
  # }
  # snippet {
  #   name     = "rl_telemetry_error"
  #   type     = "error"
  #   content  = file("${path.module}/vcl/rl_telemetry_error.vcl")
  # }

  force_destroy = false
}
