# Fastly VCL service that fronts the GCP Cloud Functions telemetry API at
# cdn.christianbrown.uk. This models the EXISTING service (id below), reconciled
# against `terraform plan` after import so the plan is clean.
#
#   terraform import fastly_service_vcl.cdn 7ieJm1LpaPnVCNb3tzURac
#
# Service id (for reference): 7ieJm1LpaPnVCNb3tzURac

# The Cloud Functions origin host, derived from the project + region so there is
# a single source of truth (e.g. europe-west2-christianbrown.cloudfunctions.net).
locals {
  backend_host = "${var.gcp_region}-${var.gcp_project}.cloudfunctions.net"
}

# The shared-secret gate value, read from the same Secret Manager secret the
# Cloud Function reads (single source of truth). Never stored in this repo or CI.
data "google_secret_manager_secret_version" "request_auth" {
  secret  = var.request_auth_secret_name
  project = var.gcp_project
}

resource "fastly_service_vcl" "cdn" {
  name = "GCP Cloud Functions API"

  default_ttl        = 3600
  stale_if_error     = true
  stale_if_error_ttl = 43200

  # Fastly-managed TLS aliases + the real hostname.
  dynamic "domain" {
    for_each = var.service_domains
    content {
      name = domain.value
    }
  }

  backend {
    name              = "GCP Cloud functions"
    address           = local.backend_host
    port              = 443
    use_ssl           = true
    ssl_check_cert    = true
    ssl_cert_hostname = local.backend_host
    ssl_sni_hostname  = local.backend_host
    override_host     = local.backend_host
    shield            = var.backend_shield
    weight            = 100
  }

  # HSTS on responses.
  header {
    name          = "Generated by force TLS and enable HSTS"
    type          = "response"
    action        = "set"
    destination   = "http.Strict-Transport-Security"
    source        = "\"max-age=31557600\""
    ignore_if_set = false
    priority      = 100
  }

  # Inject the shared-secret gate header so the origin Cloud Function accepts the
  # request without the browser ever seeing it. Value is read from Secret Manager
  # at plan/apply time — never hardcoded or committed.
  header {
    name          = "Set X-Request-Auth"
    type          = "request"
    action        = "set"
    destination   = "http.X-Request-Auth"
    source        = "\"${data.google_secret_manager_secret_version.request_auth.secret_data}\""
    ignore_if_set = false
    priority      = 10
  }

  # Strip query strings service-wide (also protects the 1-instance origin from
  # query-varied cache-busting).
  header {
    name          = "Remove querystrings"
    type          = "request"
    action        = "set"
    destination   = "url"
    source        = "req.url.path"
    ignore_if_set = false
    priority      = 10
  }

  request_setting {
    name          = "Generated by force TLS and enable HSTS"
    force_ssl     = true
    force_miss    = false
    max_stale_age = 0
  }

  force_destroy = false
}
